# -*- coding: utf-8 -*-
"""xnr and dgo TTS notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gye-64S4SDSZWDxtry0xwoufRIJLeSBu

.## Instructions
* The model and dataset are private on Huggingface, so you need a token for a user that has access to the sil-ai organization.
  * In huggingface.co, click on your user icon -> Access Tokens.
  * Create a new token
  * Under Org permissions, select SIL Global - AI
  * Check "Read access to contents of all repos in selected organizations"
  * Create token
  * Paste that token into the Secrets section in the left-sidebar of this notebook, with the name "HF_TOKEN".
  * Make sure the Notebook access column is checked.

* Some functions require a GPU, so at the top-right arrow, choose "Change runtime type" and select a GPU, e.g. "T4 GPU"
"""

!pip uninstall -y torchvision
!pip install -U speechbrain uroman datasets[audio] transformers[audio] torchaudio==2.8.0 torchcodec==0.7.0 --no-cache-dir

import os
from IPython.display import Audio as IPythonAudio, display
from datasets import load_dataset, Audio as HFAudio
from torchaudio import load as load_audio
import torch
import re
import numpy as np
import soundfile as sf
from dataclasses import dataclass
from typing import Optional

import uroman as ur
uroman = ur.Uroman()

@dataclass
class Config:
    model_name: str
    dataset_name: str
    speaker_index: int
    num_samples: int = 10
    clip_seconds: float = 3.0
    clips: int = 3
    commit: Optional[str] = None
    orthography: Optional[str] = None
    max_words: int = 40
    sr: int = 16000
    text_col: str = "text"
    speaker_model_type: str="xvect"

xnr_a = Config(
    model_name="sil-ai/xnr-tts-training-data-speecht5-a",
    commit="021efeb612e98eb8feecb45e69f982168a5de38a",
    dataset_name="sil-ai/xnr-tts-training-data",
    speaker_index=6,
    clip_seconds=3.0,
    clips=3,
    orthography="a",
    text_col="text_a"
)

xnr_b = Config(
    model_name="sil-ai/xnr-tts-training-data-speecht5-b",
    commit="397434c2bd9d8a8c939a956309a91c415549b8e4",
    dataset_name="sil-ai/xnr-tts-training-data",
    speaker_index=6,
    clip_seconds=3.0,
    clips=3,
    orthography="b",
    text_col="text_b"
)

dgo_a = Config(
    model_name="sil-ai/dgo-tts-training-data-speecht5-a",
    commit="f35556c5635854f1a501ce421a9cb24e32aaccf9",
    dataset_name="sil-ai/dgo-tts-training-data",
    speaker_index=1000,
    clip_seconds=5.0,
    clips=1,
    text_col="text_a",
)

dgo_b = Config(
    model_name="sil-ai/dgo-tts-training-data-speecht5-b",
    commit="dcda3ac3a4d0a66eb3b6fd86b9986e81644e13f4",
    dataset_name="sil-ai/dgo-tts-training-data",
    speaker_index=1000,
    clip_seconds=5.0,
    clips=1,
    text_col="text_b",
)

def trim_silence_energy(x, sr, frame_ms=30, hop_ms=10, rel_db=-45.0, pad_ms=0):
        x = x.float();
        if x.ndim > 1: x = x.mean(dim=0)
        if x.numel() == 0: return x
        m = x.abs().max()
        if m > 0: x = x / m
        frame = max(1, int(sr*frame_ms/1000)); hop = max(1, int(sr*hop_ms/1000))
        if x.numel() < frame: return x
        f = x.unfold(0, frame, hop); e = 10.0*torch.log10(f.pow(2).mean(dim=1)+1e-12)
        thr = e.median() + rel_db
        idx = (e > thr).nonzero(as_tuple=True)[0]
        if idx.numel() == 0: return x
        a, b = idx[0].item(), idx[-1].item()
        s = max(0, a*hop - int(sr*pad_ms/1000)); t = min(x.numel(), b*hop + frame + int(sr*pad_ms/1000))
        return x[s:t]

def create_speaker_embedding(
        dataset_name,
        index=0,
        num_samples=1,
        hf_token=None,
        sr=16000,
        clip_seconds=3.0,
        center=False,
        crops=3,
        aggregate="median",
        speaker_model_type="xvect"
    ):
    import torch
    from torch.nn.utils.rnn import pad_sequence
    from datasets import load_dataset, Audio
    from speechbrain.inference import EncoderClassifier

    ds = load_dataset(
        dataset_name,
        split=f"train[{index}:{index+num_samples}]",
        token=hf_token,
        cache_dir="/mnt/tts-model-cache",
    )
    ds = ds.cast_column("audio", Audio(decode=True, sampling_rate=sr))
    seg = ds.select(range(0, num_samples))

    waves, lengths, per_counts = [], [], []
    L = int(sr*clip_seconds)

    for ex in seg:
        a = torch.tensor(ex["audio"]["array"]).float()
        if a.ndim > 1: a = a.mean(dim=0)
        a = trim_silence_energy(a, sr)
        segs = []
        if a.numel() <= L:
            segs = [a]
        else:
            if center:
                s = (a.numel()-L)//2; segs = [a[s:s+L]]
            else:
                k = max(1, crops)
                idxs = torch.linspace(0, a.numel()-L, steps=k, dtype=torch.long)
                segs = [trim_silence_energy(a[i:i+L], sr) for i in idxs]
        per_counts.append(len(segs))
        waves.extend(segs)
        lengths.extend([s.numel() for s in segs])

    batch = pad_sequence(waves, batch_first=True)
    rel = torch.tensor(lengths, dtype=torch.float32); rel = rel/rel.max().clamp_min(1)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = EncoderClassifier.from_hparams(
        source=f"speechbrain/spkrec-{speaker_model_type}-voxceleb",
        run_opts={"device": device},
        savedir="/tmp/spkrec",
    )

    with torch.no_grad():
        emb = model.encode_batch(batch.to(device), rel.to(device)).squeeze(1).cpu()

    emb = torch.nn.functional.normalize(emb, dim=-1)    # L2-norm across D


    outs, p = [], 0
    for c in per_counts:
        e = emb[p:p+c]
        v = e.median(dim=0).values if aggregate == "median" else e.mean(dim=0)
        outs.append(v); p += c

    spk = torch.stack(outs).mean(dim=0).numpy()
    return spk

def run_inference_on_text(text, model_name, commit, speaker_embedding, output_filename=None, max_words=40, threshold=0.01):
    text = re.sub(r'\s+', ' ', text.strip())

    # Split into sentences
    sentences = re.split(r'([.!?]+)', text)

    # Recombine sentences with their punctuation
    sentence_list = []
    for i in range(0, len(sentences) - 1, 2):
        if i + 1 < len(sentences):
            sentence = (sentences[i] + sentences[i + 1]).strip()
            if sentence:
                sentence_list.append(sentence)

    # Handle case where text doesn't end with punctuation
    if len(sentences) % 2 == 1 and sentences[-1].strip():
        sentence_list.append(sentences[-1].strip())

    # Group sentences by word count
    text_chunks = []
    current_chunk = []
    current_word_count = 0

    for sentence in sentence_list:
        sentence_word_count = len(sentence.split())

        # If adding this sentence would exceed max_words and we have sentences in current chunk
        if current_word_count + sentence_word_count > max_words and current_chunk:
            # Finish current chunk and start new one
            text_chunks.append(' '.join(current_chunk))
            current_chunk = [sentence]
            current_word_count = sentence_word_count
        else:
            # Add to current chunk
            current_chunk.append(sentence)
            current_word_count += sentence_word_count

    # Add the last chunk if it has content
    if current_chunk:
        text_chunks.append(' '.join(current_chunk))

    print(f"Split text into {len(text_chunks)} chunks (max {max_words} words each):")
    for i, chunk in enumerate(text_chunks, 1):
        word_count = len(chunk.split())
        # print(f"  Chunk {i}: {word_count} words - {chunk[:70]}...")

    speeches = []

    for i, sentence in enumerate(text_chunks):
        if sentence.strip():
            print(f"Processing: {sentence.strip()}")
            # If the sentence isn't roman script, print the romanizedversion
            if re.search(r'[^\x00-\x7F]', sentence.strip()):
                romanized = uroman.romanize_string(sentence.strip())
                print(f"Romanized: {romanized}")


            speech = run_inference(model_name, sentence.strip(), speaker_embedding=speaker_embedding, commit=commit, threshold=threshold)
            speeches.append(speech)
            if output_filename:
                new_filename = f'{output_filename.split(".")[:-1]}-{i:04d}-{output_filename.split(".")[-1]}'
                sf.write(new_filename, speech, 16000)

    return speeches

def run_inference(model_name, text_prompt, speaker_embedding, commit=None, threshold=0.01):
    from transformers import SpeechT5ForTextToSpeech, SpeechT5Processor, SpeechT5HifiGan
    import torch

    device = "cuda" if torch.cuda.is_available() else "cpu"

    vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan").to(device)
    if commit:
        model = SpeechT5ForTextToSpeech.from_pretrained(model_name, revision=commit).to(device)
    else:
        model = SpeechT5ForTextToSpeech.from_pretrained(model_name).to(device)
    # processor = SpeechT5Processor.from_pretrained("microsoft/speecht5_tts")
    processor = SpeechT5Processor.from_pretrained(model_name)

    inputs = processor(text=text_prompt, return_tensors="pt")
    input_ids = inputs["input_ids"].to(device)
    speaker_embedding = torch.tensor(speaker_embedding).unsqueeze(0).to(device)

    spectrogram = model.generate_speech(input_ids, speaker_embedding, threshold=threshold)
    print(f"Generated spectrogram shape: {spectrogram.shape}")
    with torch.no_grad():
        speech = vocoder(spectrogram)
    print(f"Generated speech shape: {speech.shape}")
    return speech.cpu().numpy()

# text = "एह सुअर्गदूत परमेसरे दी जै-जैकार करदे हन, कने तिहनां दे हुक्मैं जो मनदे हन।"  # orthography A
# text = 'फिरी तिहनां ग्लाया, "मैं तुसां जो सच्चाई दसदा भई जेहड़ा अप्पु जो दीन बणांहगा, कने इस बच्चे साहई साफ दिल बहणगा, सैह ई परमेसरे दे राज्ये च सारेआं ते बड्डा है।'  # orthography B

text = "अऊं इनेंगी खत्‍म करने नेई, बल्‍कि पूरा करने आस्‍ते आया ऐं।"
# text = "अऊं इनेङ्गी खत्म करने नेई, बल्कि पूरा करने आस्ते आया ऐं।"

# config = xnr_a
# config = xnr_b
config = dgo_a
# config = dgo_b

speaker_embedding = create_speaker_embedding(dataset_name=config.dataset_name, num_samples=1, aggregate="mean", index=config.speaker_index, clip_seconds=config.clip_seconds, speaker_model_type=config.speaker_model_type, crops=config.clips)

speech = run_inference_on_text(text=text, model_name=config.model_name, commit=config.commit, speaker_embedding=speaker_embedding, max_words=config.max_words, threshold=0.01)
display(IPythonAudio(data=speech, autoplay=True, rate=16000))

config.commit